[project]
name = "02-mini-transformer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "julax",
]

[tool.uv.sources]
julax = { workspace = true }
